// Generated by scripts/optimize-images.mjs — do not edit by hand.
import type { ResponsiveImage } from "../../Picture"

import auroraDanAvif480 from "./auroraDan-480.avif"
import auroraDanWebp480 from "./auroraDan-480.webp"
import auroraDanAvif793 from "./auroraDan-793.avif"
import auroraDanWebp793 from "./auroraDan-793.webp"
import clowndanAvif480 from "./clowndan-480.avif"
import clowndanWebp480 from "./clowndan-480.webp"
import clowndanAvif735 from "./clowndan-735.avif"
import clowndanWebp735 from "./clowndan-735.webp"
import confirmClipPosterAvif324 from "./confirm-clip-poster-324.avif"
import confirmClipPosterWebp324 from "./confirm-clip-poster-324.webp"
import deadDanAvif480 from "./deadDan-480.avif"
import deadDanWebp480 from "./deadDan-480.webp"
import deadDanAvif800 from "./deadDan-800.avif"
import deadDanWebp800 from "./deadDan-800.webp"
import deadDanAvif1179 from "./deadDan-1179.avif"
import deadDanWebp1179 from "./deadDan-1179.webp"
import gitDanAvif480 from "./gitDan-480.avif"
import gitDanWebp480 from "./gitDan-480.webp"
import gitDanAvif800 from "./gitDan-800.avif"
import gitDanWebp800 from "./gitDan-800.webp"
import gitDanAvif1176 from "./gitDan-1176.avif"
import gitDanWebp1176 from "./gitDan-1176.webp"
import heroMobilePosterAvif480 from "./hero-mobile-poster-480.avif"
import heroMobilePosterWebp480 from "./hero-mobile-poster-480.webp"
import heroMobilePosterAvif720 from "./hero-mobile-poster-720.avif"
import heroMobilePosterWebp720 from "./hero-mobile-poster-720.webp"
import normieDanAvif480 from "./normieDan-480.avif"
import normieDanWebp480 from "./normieDan-480.webp"
import normieDanAvif800 from "./normieDan-800.avif"
import normieDanWebp800 from "./normieDan-800.webp"
import normieDanAvif1200 from "./normieDan-1200.avif"
import normieDanWebp1200 from "./normieDan-1200.webp"
import normieDanAvif1472 from "./normieDan-1472.avif"
import normieDanWebp1472 from "./normieDan-1472.webp"
import omgDanAvif480 from "./omgDan-480.avif"
import omgDanWebp480 from "./omgDan-480.webp"
import omgDanAvif800 from "./omgDan-800.avif"
import omgDanWebp800 from "./omgDan-800.webp"
import omgDanAvif1200 from "./omgDan-1200.avif"
import omgDanWebp1200 from "./omgDan-1200.webp"
import omgDanAvif1600 from "./omgDan-1600.avif"
import omgDanWebp1600 from "./omgDan-1600.webp"
import bookAvif480 from "./portrait-book-480.avif"
import bookWebp480 from "./portrait-book-480.webp"
import bookAvif800 from "./portrait-book-800.avif"
import bookWebp800 from "./portrait-book-800.webp"
import bookAvif1200 from "./portrait-book-1200.avif"
import bookWebp1200 from "./portrait-book-1200.webp"
import bookAvif1600 from "./portrait-book-1600.avif"
import bookWebp1600 from "./portrait-book-1600.webp"
import childhoodPinkAvif480 from "./portrait-childhood-pink-480.avif"
import childhoodPinkWebp480 from "./portrait-childhood-pink-480.webp"
import childhoodPinkAvif607 from "./portrait-childhood-pink-607.avif"
import childhoodPinkWebp607 from "./portrait-childhood-pink-607.webp"
import childhoodTealAvif480 from "./portrait-childhood-teal-480.avif"
import childhoodTealWebp480 from "./portrait-childhood-teal-480.webp"
import childhoodTealAvif648 from "./portrait-childhood-teal-648.avif"
import childhoodTealWebp648 from "./portrait-childhood-teal-648.webp"
import facepaintAvif480 from "./portrait-facepaint-480.avif"
import facepaintWebp480 from "./portrait-facepaint-480.webp"
import facepaintAvif800 from "./portrait-facepaint-800.avif"
import facepaintWebp800 from "./portrait-facepaint-800.webp"
import facepaintAvif1106 from "./portrait-facepaint-1106.avif"
import facepaintWebp1106 from "./portrait-facepaint-1106.webp"
import giftAvif480 from "./portrait-gift-480.avif"
import giftWebp480 from "./portrait-gift-480.webp"
import giftAvif800 from "./portrait-gift-800.avif"
import giftWebp800 from "./portrait-gift-800.webp"
import giftAvif1200 from "./portrait-gift-1200.avif"
import giftWebp1200 from "./portrait-gift-1200.webp"
import giftAvif1600 from "./portrait-gift-1600.avif"
import giftWebp1600 from "./portrait-gift-1600.webp"
import mirrorAvif411 from "./portrait-mirror-411.avif"
import mirrorWebp411 from "./portrait-mirror-411.webp"
import monkeyAvif480 from "./portrait-monkey-480.avif"
import monkeyWebp480 from "./portrait-monkey-480.webp"
import monkeyAvif800 from "./portrait-monkey-800.avif"
import monkeyWebp800 from "./portrait-monkey-800.webp"
import monkeyAvif1034 from "./portrait-monkey-1034.avif"
import monkeyWebp1034 from "./portrait-monkey-1034.webp"
import robotAvif480 from "./portrait-robot-480.avif"
import robotWebp480 from "./portrait-robot-480.webp"
import robotAvif800 from "./portrait-robot-800.avif"
import robotWebp800 from "./portrait-robot-800.webp"
import robotAvif1200 from "./portrait-robot-1200.avif"
import robotWebp1200 from "./portrait-robot-1200.webp"
import robotAvif1600 from "./portrait-robot-1600.avif"
import robotWebp1600 from "./portrait-robot-1600.webp"
import selfieAvif480 from "./portrait-selfie-480.avif"
import selfieWebp480 from "./portrait-selfie-480.webp"
import selfieAvif791 from "./portrait-selfie-791.avif"
import selfieWebp791 from "./portrait-selfie-791.webp"
import shadesAvif480 from "./portrait-shades-480.avif"
import shadesWebp480 from "./portrait-shades-480.webp"
import shadesAvif800 from "./portrait-shades-800.avif"
import shadesWebp800 from "./portrait-shades-800.webp"
import shadesAvif1200 from "./portrait-shades-1200.avif"
import shadesWebp1200 from "./portrait-shades-1200.webp"
import shadesAvif1600 from "./portrait-shades-1600.avif"
import shadesWebp1600 from "./portrait-shades-1600.webp"
import stripesAvif480 from "./portrait-stripes-480.avif"
import stripesWebp480 from "./portrait-stripes-480.webp"
import stripesAvif800 from "./portrait-stripes-800.avif"
import stripesWebp800 from "./portrait-stripes-800.webp"
import stripesAvif1179 from "./portrait-stripes-1179.avif"
import stripesWebp1179 from "./portrait-stripes-1179.webp"
import waveAvif480 from "./portrait-wave-480.avif"
import waveWebp480 from "./portrait-wave-480.webp"
import waveAvif764 from "./portrait-wave-764.avif"
import waveWebp764 from "./portrait-wave-764.webp"
import smartLittleDanAvif480 from "./smartLittleDan-480.avif"
import smartLittleDanWebp480 from "./smartLittleDan-480.webp"
import smartLittleDanAvif800 from "./smartLittleDan-800.avif"
import smartLittleDanWebp800 from "./smartLittleDan-800.webp"
import smartLittleDanAvif1023 from "./smartLittleDan-1023.avif"
import smartLittleDanWebp1023 from "./smartLittleDan-1023.webp"
import smileDanAvif480 from "./smileDan-480.avif"
import smileDanWebp480 from "./smileDan-480.webp"
import smileDanAvif800 from "./smileDan-800.avif"
import smileDanWebp800 from "./smileDan-800.webp"
import smileDanAvif1200 from "./smileDan-1200.avif"
import smileDanWebp1200 from "./smileDan-1200.webp"
import smileDanAvif1600 from "./smileDan-1600.avif"
import smileDanWebp1600 from "./smileDan-1600.webp"
import stemDanAvif480 from "./stemDan-480.avif"
import stemDanWebp480 from "./stemDan-480.webp"
import stemDanAvif800 from "./stemDan-800.avif"
import stemDanWebp800 from "./stemDan-800.webp"
import stemDanAvif1200 from "./stemDan-1200.avif"
import stemDanWebp1200 from "./stemDan-1200.webp"
import stemDanAvif1600 from "./stemDan-1600.avif"
import stemDanWebp1600 from "./stemDan-1600.webp"
import wowDanAvif480 from "./wowDan-480.avif"
import wowDanWebp480 from "./wowDan-480.webp"
import wowDanAvif800 from "./wowDan-800.avif"
import wowDanWebp800 from "./wowDan-800.webp"
import wowDanAvif1200 from "./wowDan-1200.avif"
import wowDanWebp1200 from "./wowDan-1200.webp"
import wowDanAvif1600 from "./wowDan-1600.avif"
import wowDanWebp1600 from "./wowDan-1600.webp"

export const auroraDan: ResponsiveImage = {
  avif: [`${auroraDanAvif480} 480w`, `${auroraDanAvif793} 793w`].join(", "),
  webp: [`${auroraDanWebp480} 480w`, `${auroraDanWebp793} 793w`].join(", "),
  src: auroraDanWebp793,
  width: 793,
  height: 1128,
}

export const clowndan: ResponsiveImage = {
  avif: [`${clowndanAvif480} 480w`, `${clowndanAvif735} 735w`].join(", "),
  webp: [`${clowndanWebp480} 480w`, `${clowndanWebp735} 735w`].join(", "),
  src: clowndanWebp735,
  width: 735,
  height: 1816,
}

export const confirmClipPoster: ResponsiveImage = {
  avif: [`${confirmClipPosterAvif324} 324w`].join(", "),
  webp: [`${confirmClipPosterWebp324} 324w`].join(", "),
  src: confirmClipPosterWebp324,
  width: 324,
  height: 324,
}

export const deadDan: ResponsiveImage = {
  avif: [`${deadDanAvif480} 480w`, `${deadDanAvif800} 800w`, `${deadDanAvif1179} 1179w`].join(", "),
  webp: [`${deadDanWebp480} 480w`, `${deadDanWebp800} 800w`, `${deadDanWebp1179} 1179w`].join(", "),
  src: deadDanWebp1179,
  width: 1179,
  height: 1421,
}

export const gitDan: ResponsiveImage = {
  avif: [`${gitDanAvif480} 480w`, `${gitDanAvif800} 800w`, `${gitDanAvif1176} 1176w`].join(", "),
  webp: [`${gitDanWebp480} 480w`, `${gitDanWebp800} 800w`, `${gitDanWebp1176} 1176w`].join(", "),
  src: gitDanWebp1176,
  width: 1176,
  height: 1034,
}

export const heroMobilePoster: ResponsiveImage = {
  avif: [`${heroMobilePosterAvif480} 480w`, `${heroMobilePosterAvif720} 720w`].join(", "),
  webp: [`${heroMobilePosterWebp480} 480w`, `${heroMobilePosterWebp720} 720w`].join(", "),
  src: heroMobilePosterWebp720,
  width: 720,
  height: 1280,
}

export const normieDan: ResponsiveImage = {
  avif: [`${normieDanAvif480} 480w`, `${normieDanAvif800} 800w`, `${normieDanAvif1200} 1200w`, `${normieDanAvif1472} 1472w`].join(", "),
  webp: [`${normieDanWebp480} 480w`, `${normieDanWebp800} 800w`, `${normieDanWebp1200} 1200w`, `${normieDanWebp1472} 1472w`].join(", "),
  src: normieDanWebp1472,
  width: 1472,
  height: 2797,
}

export const omgDan: ResponsiveImage = {
  avif: [`${omgDanAvif480} 480w`, `${omgDanAvif800} 800w`, `${omgDanAvif1200} 1200w`, `${omgDanAvif1600} 1600w`].join(", "),
  webp: [`${omgDanWebp480} 480w`, `${omgDanWebp800} 800w`, `${omgDanWebp1200} 1200w`, `${omgDanWebp1600} 1600w`].join(", "),
  src: omgDanWebp1600,
  width: 1600,
  height: 1072,
}

export const book: ResponsiveImage = {
  avif: [`${bookAvif480} 480w`, `${bookAvif800} 800w`, `${bookAvif1200} 1200w`, `${bookAvif1600} 1600w`].join(", "),
  webp: [`${bookWebp480} 480w`, `${bookWebp800} 800w`, `${bookWebp1200} 1200w`, `${bookWebp1600} 1600w`].join(", "),
  src: bookWebp1600,
  width: 1600,
  height: 1497,
}

export const childhoodPink: ResponsiveImage = {
  avif: [`${childhoodPinkAvif480} 480w`, `${childhoodPinkAvif607} 607w`].join(", "),
  webp: [`${childhoodPinkWebp480} 480w`, `${childhoodPinkWebp607} 607w`].join(", "),
  src: childhoodPinkWebp607,
  width: 607,
  height: 1424,
}

export const childhoodTeal: ResponsiveImage = {
  avif: [`${childhoodTealAvif480} 480w`, `${childhoodTealAvif648} 648w`].join(", "),
  webp: [`${childhoodTealWebp480} 480w`, `${childhoodTealWebp648} 648w`].join(", "),
  src: childhoodTealWebp648,
  width: 648,
  height: 1483,
}

export const facepaint: ResponsiveImage = {
  avif: [`${facepaintAvif480} 480w`, `${facepaintAvif800} 800w`, `${facepaintAvif1106} 1106w`].join(", "),
  webp: [`${facepaintWebp480} 480w`, `${facepaintWebp800} 800w`, `${facepaintWebp1106} 1106w`].join(", "),
  src: facepaintWebp1106,
  width: 1106,
  height: 1351,
}

export const gift: ResponsiveImage = {
  avif: [`${giftAvif480} 480w`, `${giftAvif800} 800w`, `${giftAvif1200} 1200w`, `${giftAvif1600} 1600w`].join(", "),
  webp: [`${giftWebp480} 480w`, `${giftWebp800} 800w`, `${giftWebp1200} 1200w`, `${giftWebp1600} 1600w`].join(", "),
  src: giftWebp1600,
  width: 1600,
  height: 2396,
}

export const mirror: ResponsiveImage = {
  avif: [`${mirrorAvif411} 411w`].join(", "),
  webp: [`${mirrorWebp411} 411w`].join(", "),
  src: mirrorWebp411,
  width: 411,
  height: 750,
}

export const monkey: ResponsiveImage = {
  avif: [`${monkeyAvif480} 480w`, `${monkeyAvif800} 800w`, `${monkeyAvif1034} 1034w`].join(", "),
  webp: [`${monkeyWebp480} 480w`, `${monkeyWebp800} 800w`, `${monkeyWebp1034} 1034w`].join(", "),
  src: monkeyWebp1034,
  width: 1034,
  height: 1176,
}

export const robot: ResponsiveImage = {
  avif: [`${robotAvif480} 480w`, `${robotAvif800} 800w`, `${robotAvif1200} 1200w`, `${robotAvif1600} 1600w`].join(", "),
  webp: [`${robotWebp480} 480w`, `${robotWebp800} 800w`, `${robotWebp1200} 1200w`, `${robotWebp1600} 1600w`].join(", "),
  src: robotWebp1600,
  width: 1600,
  height: 2420,
}

export const selfie: ResponsiveImage = {
  avif: [`${selfieAvif480} 480w`, `${selfieAvif791} 791w`].join(", "),
  webp: [`${selfieWebp480} 480w`, `${selfieWebp791} 791w`].join(", "),
  src: selfieWebp791,
  width: 791,
  height: 1613,
}

export const shades: ResponsiveImage = {
  avif: [`${shadesAvif480} 480w`, `${shadesAvif800} 800w`, `${shadesAvif1200} 1200w`, `${shadesAvif1600} 1600w`].join(", "),
  webp: [`${shadesWebp480} 480w`, `${shadesWebp800} 800w`, `${shadesWebp1200} 1200w`, `${shadesWebp1600} 1600w`].join(", "),
  src: shadesWebp1600,
  width: 1600,
  height: 3044,
}

export const stripes: ResponsiveImage = {
  avif: [`${stripesAvif480} 480w`, `${stripesAvif800} 800w`, `${stripesAvif1179} 1179w`].join(", "),
  webp: [`${stripesWebp480} 480w`, `${stripesWebp800} 800w`, `${stripesWebp1179} 1179w`].join(", "),
  src: stripesWebp1179,
  width: 1179,
  height: 1744,
}

export const wave: ResponsiveImage = {
  avif: [`${waveAvif480} 480w`, `${waveAvif764} 764w`].join(", "),
  webp: [`${waveWebp480} 480w`, `${waveWebp764} 764w`].join(", "),
  src: waveWebp764,
  width: 764,
  height: 1713,
}

export const smartLittleDan: ResponsiveImage = {
  avif: [`${smartLittleDanAvif480} 480w`, `${smartLittleDanAvif800} 800w`, `${smartLittleDanAvif1023} 1023w`].join(", "),
  webp: [`${smartLittleDanWebp480} 480w`, `${smartLittleDanWebp800} 800w`, `${smartLittleDanWebp1023} 1023w`].join(", "),
  src: smartLittleDanWebp1023,
  width: 1023,
  height: 1764,
}

export const smileDan: ResponsiveImage = {
  avif: [`${smileDanAvif480} 480w`, `${smileDanAvif800} 800w`, `${smileDanAvif1200} 1200w`, `${smileDanAvif1600} 1600w`].join(", "),
  webp: [`${smileDanWebp480} 480w`, `${smileDanWebp800} 800w`, `${smileDanWebp1200} 1200w`, `${smileDanWebp1600} 1600w`].join(", "),
  src: smileDanWebp1600,
  width: 1600,
  height: 2558,
}

export const stemDan: ResponsiveImage = {
  avif: [`${stemDanAvif480} 480w`, `${stemDanAvif800} 800w`, `${stemDanAvif1200} 1200w`, `${stemDanAvif1600} 1600w`].join(", "),
  webp: [`${stemDanWebp480} 480w`, `${stemDanWebp800} 800w`, `${stemDanWebp1200} 1200w`, `${stemDanWebp1600} 1600w`].join(", "),
  src: stemDanWebp1600,
  width: 1600,
  height: 1909,
}

export const wowDan: ResponsiveImage = {
  avif: [`${wowDanAvif480} 480w`, `${wowDanAvif800} 800w`, `${wowDanAvif1200} 1200w`, `${wowDanAvif1600} 1600w`].join(", "),
  webp: [`${wowDanWebp480} 480w`, `${wowDanWebp800} 800w`, `${wowDanWebp1200} 1200w`, `${wowDanWebp1600} 1600w`].join(", "),
  src: wowDanWebp1600,
  width: 1600,
  height: 1045,
}
