// Generated by scripts/optimize-images.mjs — do not edit by hand.
import type { ResponsiveImage } from "../../Picture"

import doodleCakeAvif480 from "./doodle-cake-480.avif"
import doodleCakeWebp480 from "./doodle-cake-480.webp"
import doodleCakeAvif563 from "./doodle-cake-563.avif"
import doodleCakeWebp563 from "./doodle-cake-563.webp"
import bookAvif480 from "./portrait-book-480.avif"
import bookWebp480 from "./portrait-book-480.webp"
import bookAvif800 from "./portrait-book-800.avif"
import bookWebp800 from "./portrait-book-800.webp"
import bookAvif1200 from "./portrait-book-1200.avif"
import bookWebp1200 from "./portrait-book-1200.webp"
import bookAvif1600 from "./portrait-book-1600.avif"
import bookWebp1600 from "./portrait-book-1600.webp"
import childhoodPinkAvif480 from "./portrait-childhood-pink-480.avif"
import childhoodPinkWebp480 from "./portrait-childhood-pink-480.webp"
import childhoodPinkAvif607 from "./portrait-childhood-pink-607.avif"
import childhoodPinkWebp607 from "./portrait-childhood-pink-607.webp"
import childhoodTealAvif480 from "./portrait-childhood-teal-480.avif"
import childhoodTealWebp480 from "./portrait-childhood-teal-480.webp"
import childhoodTealAvif648 from "./portrait-childhood-teal-648.avif"
import childhoodTealWebp648 from "./portrait-childhood-teal-648.webp"
import facepaintAvif480 from "./portrait-facepaint-480.avif"
import facepaintWebp480 from "./portrait-facepaint-480.webp"
import facepaintAvif800 from "./portrait-facepaint-800.avif"
import facepaintWebp800 from "./portrait-facepaint-800.webp"
import facepaintAvif1106 from "./portrait-facepaint-1106.avif"
import facepaintWebp1106 from "./portrait-facepaint-1106.webp"
import giftAvif480 from "./portrait-gift-480.avif"
import giftWebp480 from "./portrait-gift-480.webp"
import giftAvif800 from "./portrait-gift-800.avif"
import giftWebp800 from "./portrait-gift-800.webp"
import giftAvif1200 from "./portrait-gift-1200.avif"
import giftWebp1200 from "./portrait-gift-1200.webp"
import giftAvif1600 from "./portrait-gift-1600.avif"
import giftWebp1600 from "./portrait-gift-1600.webp"
import mirrorAvif411 from "./portrait-mirror-411.avif"
import mirrorWebp411 from "./portrait-mirror-411.webp"
import monkeyAvif480 from "./portrait-monkey-480.avif"
import monkeyWebp480 from "./portrait-monkey-480.webp"
import monkeyAvif800 from "./portrait-monkey-800.avif"
import monkeyWebp800 from "./portrait-monkey-800.webp"
import monkeyAvif1034 from "./portrait-monkey-1034.avif"
import monkeyWebp1034 from "./portrait-monkey-1034.webp"
import robotAvif480 from "./portrait-robot-480.avif"
import robotWebp480 from "./portrait-robot-480.webp"
import robotAvif800 from "./portrait-robot-800.avif"
import robotWebp800 from "./portrait-robot-800.webp"
import robotAvif1200 from "./portrait-robot-1200.avif"
import robotWebp1200 from "./portrait-robot-1200.webp"
import robotAvif1600 from "./portrait-robot-1600.avif"
import robotWebp1600 from "./portrait-robot-1600.webp"
import selfieAvif480 from "./portrait-selfie-480.avif"
import selfieWebp480 from "./portrait-selfie-480.webp"
import selfieAvif791 from "./portrait-selfie-791.avif"
import selfieWebp791 from "./portrait-selfie-791.webp"
import shadesAvif480 from "./portrait-shades-480.avif"
import shadesWebp480 from "./portrait-shades-480.webp"
import shadesAvif800 from "./portrait-shades-800.avif"
import shadesWebp800 from "./portrait-shades-800.webp"
import shadesAvif1200 from "./portrait-shades-1200.avif"
import shadesWebp1200 from "./portrait-shades-1200.webp"
import shadesAvif1600 from "./portrait-shades-1600.avif"
import shadesWebp1600 from "./portrait-shades-1600.webp"
import stripesAvif480 from "./portrait-stripes-480.avif"
import stripesWebp480 from "./portrait-stripes-480.webp"
import stripesAvif800 from "./portrait-stripes-800.avif"
import stripesWebp800 from "./portrait-stripes-800.webp"
import stripesAvif1179 from "./portrait-stripes-1179.avif"
import stripesWebp1179 from "./portrait-stripes-1179.webp"
import waveAvif480 from "./portrait-wave-480.avif"
import waveWebp480 from "./portrait-wave-480.webp"
import waveAvif764 from "./portrait-wave-764.avif"
import waveWebp764 from "./portrait-wave-764.webp"

export const doodleCake: ResponsiveImage = {
  avif: [`${doodleCakeAvif480} 480w`, `${doodleCakeAvif563} 563w`].join(", "),
  webp: [`${doodleCakeWebp480} 480w`, `${doodleCakeWebp563} 563w`].join(", "),
  src: doodleCakeWebp563,
  width: 563,
  height: 554,
}

export const book: ResponsiveImage = {
  avif: [`${bookAvif480} 480w`, `${bookAvif800} 800w`, `${bookAvif1200} 1200w`, `${bookAvif1600} 1600w`].join(", "),
  webp: [`${bookWebp480} 480w`, `${bookWebp800} 800w`, `${bookWebp1200} 1200w`, `${bookWebp1600} 1600w`].join(", "),
  src: bookWebp1600,
  width: 1600,
  height: 1497,
}

export const childhoodPink: ResponsiveImage = {
  avif: [`${childhoodPinkAvif480} 480w`, `${childhoodPinkAvif607} 607w`].join(", "),
  webp: [`${childhoodPinkWebp480} 480w`, `${childhoodPinkWebp607} 607w`].join(", "),
  src: childhoodPinkWebp607,
  width: 607,
  height: 1424,
}

export const childhoodTeal: ResponsiveImage = {
  avif: [`${childhoodTealAvif480} 480w`, `${childhoodTealAvif648} 648w`].join(", "),
  webp: [`${childhoodTealWebp480} 480w`, `${childhoodTealWebp648} 648w`].join(", "),
  src: childhoodTealWebp648,
  width: 648,
  height: 1483,
}

export const facepaint: ResponsiveImage = {
  avif: [`${facepaintAvif480} 480w`, `${facepaintAvif800} 800w`, `${facepaintAvif1106} 1106w`].join(", "),
  webp: [`${facepaintWebp480} 480w`, `${facepaintWebp800} 800w`, `${facepaintWebp1106} 1106w`].join(", "),
  src: facepaintWebp1106,
  width: 1106,
  height: 1351,
}

export const gift: ResponsiveImage = {
  avif: [`${giftAvif480} 480w`, `${giftAvif800} 800w`, `${giftAvif1200} 1200w`, `${giftAvif1600} 1600w`].join(", "),
  webp: [`${giftWebp480} 480w`, `${giftWebp800} 800w`, `${giftWebp1200} 1200w`, `${giftWebp1600} 1600w`].join(", "),
  src: giftWebp1600,
  width: 1600,
  height: 2396,
}

export const mirror: ResponsiveImage = {
  avif: [`${mirrorAvif411} 411w`].join(", "),
  webp: [`${mirrorWebp411} 411w`].join(", "),
  src: mirrorWebp411,
  width: 411,
  height: 750,
}

export const monkey: ResponsiveImage = {
  avif: [`${monkeyAvif480} 480w`, `${monkeyAvif800} 800w`, `${monkeyAvif1034} 1034w`].join(", "),
  webp: [`${monkeyWebp480} 480w`, `${monkeyWebp800} 800w`, `${monkeyWebp1034} 1034w`].join(", "),
  src: monkeyWebp1034,
  width: 1034,
  height: 1176,
}

export const robot: ResponsiveImage = {
  avif: [`${robotAvif480} 480w`, `${robotAvif800} 800w`, `${robotAvif1200} 1200w`, `${robotAvif1600} 1600w`].join(", "),
  webp: [`${robotWebp480} 480w`, `${robotWebp800} 800w`, `${robotWebp1200} 1200w`, `${robotWebp1600} 1600w`].join(", "),
  src: robotWebp1600,
  width: 1600,
  height: 2420,
}

export const selfie: ResponsiveImage = {
  avif: [`${selfieAvif480} 480w`, `${selfieAvif791} 791w`].join(", "),
  webp: [`${selfieWebp480} 480w`, `${selfieWebp791} 791w`].join(", "),
  src: selfieWebp791,
  width: 791,
  height: 1613,
}

export const shades: ResponsiveImage = {
  avif: [`${shadesAvif480} 480w`, `${shadesAvif800} 800w`, `${shadesAvif1200} 1200w`, `${shadesAvif1600} 1600w`].join(", "),
  webp: [`${shadesWebp480} 480w`, `${shadesWebp800} 800w`, `${shadesWebp1200} 1200w`, `${shadesWebp1600} 1600w`].join(", "),
  src: shadesWebp1600,
  width: 1600,
  height: 3044,
}

export const stripes: ResponsiveImage = {
  avif: [`${stripesAvif480} 480w`, `${stripesAvif800} 800w`, `${stripesAvif1179} 1179w`].join(", "),
  webp: [`${stripesWebp480} 480w`, `${stripesWebp800} 800w`, `${stripesWebp1179} 1179w`].join(", "),
  src: stripesWebp1179,
  width: 1179,
  height: 1744,
}

export const wave: ResponsiveImage = {
  avif: [`${waveAvif480} 480w`, `${waveAvif764} 764w`].join(", "),
  webp: [`${waveWebp480} 480w`, `${waveWebp764} 764w`].join(", "),
  src: waveWebp764,
  width: 764,
  height: 1713,
}
