// Converts the original photos in src/assets into responsive AVIF + WebP
// variants (max 1600px wide) and writes a typed manifest that the app imports.
// The originals are never imported, so they stay out of the bundle.
//
// Usage: pnpm images
import fs from "node:fs/promises"
import path from "node:path"
import sharp from "sharp"

const SRC = path.resolve("src/assets")
const OUT = path.resolve("src/assets/optimized")
const STEPS = [480, 800, 1200, 1600]
const MAX = 1600

const toKey = (file) =>
  file
    .replace(/\.\w+$/, "")
    .replace(/^(namjoon|portrait)-/, "")
    .replace(/-(\w)/g, (_, c) => c.toUpperCase())

await fs.rm(OUT, { recursive: true, force: true })
await fs.mkdir(OUT, { recursive: true })

const files = (await fs.readdir(SRC)).filter((f) => /\.(png|jpe?g)$/i.test(f))
const entries = []

for (const file of files) {
  const input = path.join(SRC, file)
  const meta = await sharp(input).metadata()
  const base = file.replace(/\.\w+$/, "")
  const top = Math.min(meta.width, MAX)
  const widths = [...STEPS.filter((w) => w < top), top]
  const height = Math.round((top / meta.width) * meta.height)
  const variants = []

  for (const w of widths) {
    const resized = sharp(input).resize({ width: w })
    await resized
      .clone()
      .avif({ quality: 52, effort: 4 })
      .toFile(path.join(OUT, `${base}-${w}.avif`))
    await resized
      .clone()
      .webp({ quality: 76, alphaQuality: 85, effort: 5 })
      .toFile(path.join(OUT, `${base}-${w}.webp`))
    variants.push(w)
  }

  entries.push({ key: toKey(file), base, width: top, height, variants })
  console.log(`${file}: ${widths.join(", ")}`)
}

const lines = [
  "// Generated by scripts/optimize-images.mjs — do not edit by hand.",
  'import type { ResponsiveImage } from "../../Picture"',
  "",
]
for (const e of entries) {
  for (const w of e.variants) {
    lines.push(`import ${e.key}Avif${w} from "./${e.base}-${w}.avif"`)
    lines.push(`import ${e.key}Webp${w} from "./${e.base}-${w}.webp"`)
  }
}
lines.push("")
for (const e of entries) {
  const set = (fmt) =>
    e.variants.map((w) => `\`\${${e.key}${fmt}${w}} ${w}w\``).join(", ")
  const last = e.variants[e.variants.length - 1]
  lines.push(`export const ${e.key}: ResponsiveImage = {`)
  lines.push(`  avif: [${set("Avif")}].join(", "),`)
  lines.push(`  webp: [${set("Webp")}].join(", "),`)
  lines.push(`  src: ${e.key}Webp${last},`)
  lines.push(`  width: ${e.width},`)
  lines.push(`  height: ${e.height},`)
  lines.push("}")
  lines.push("")
}
await fs.writeFile(path.join(OUT, "index.ts"), lines.join("\n"))
